name: CI/CD Pipeline


on:
  push:
    branches:
      - prod

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y apt-transport-https ca-certificates gnupg
    
    - name: Add gcloud CLI distribution
      run: |
        echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list

    - name: Acquire public key
      run: |
        curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -

    - name: Install gcloud CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y google-cloud-sdk

    - name: Install GKE gcloud auth plugin
      run: |
        sudo apt-get install -y google-cloud-sdk-gke-gcloud-auth-plugin

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCLOUD_SERVICE_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCLOUD_PROJECT }}
        export_default_credentials: true

    - name: Configure docker to use Artifact Registry
      run: gcloud auth configure-docker ${{ secrets.REGION }}-docker.pkg.dev

    - name: Build and push Docker images
      run: |
        cd api/ && docker build -t ${{ secrets.BACKEND_IMAGE_URL }}:${GITHUB_SHA} .
        : # cd ../web/ && docker build -t ${{ secrets.FRONTEND_IMAGE_URL }}:${GITHUB_SHA} -f Dockerfile .
        : # docker build -t ${{ secrets.NGINX_IMAGE_URL }}:${GITHUB_SHA} -f Dockerfile.nginx .
         docker push ${{ secrets.BACKEND_IMAGE_URL }}:${GITHUB_SHA}
        : # docker push ${{ secrets.FRONTEND_IMAGE_URL }}:${GITHUB_SHA}
        : # docker push ${{ secrets.NGINX_IMAGE_URL }}:${GITHUB_SHA}

    - name: Deploy to GKE
      run: |
        gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER }} --zone ${{ secrets.GKE_ZONE }}
        kubectl set image deployment/backend-deployment backend=${{ secrets.BACKEND_IMAGE_TAG }}:${GITHUB_SHA}
        : # kubectl set image deployment/frontend-deployment frontend=${{ secrets.FRONTEND_IMAGE_TAG }}:${GITHUB_SHA}
        : # kubectl set image deployment/nginx-deployment nginx=${{ secrets.NGINX_IMAGE_TAG }}:${GITHUB_SHA}


