name: CI/CD Pipeline

on:
  push:
    branches:
      - prod

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCLOUD_PROJECT }}
        service_account_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
        export_deafult_credentias: true

    - name: Configure docker to use Artifact Registry
      run: gcloud auth configure-docker ${{ secrets.REGION }}-docker.pkg.dev

    - name: Build and push backend
      uses: docker/build-push-action@v5
      with:
        context: ./api
        file: Dockerfile
        push: true
        tags: ${GITHUB_SHA}
    
    - name: Build and push frontend
      uses: docker/build-push-action@v5
      with:
        context: ./web
        file: Dockerfile
        push: true
        tags: ${GITHUB_SHA}

    - name: Build and push nginx
      uses: docker/build-push-action@v5
      with:
        context: ./web
        file: Dockerfile.nginx
        push: true
        tags: ${GITHUB_SHA}

    - name: Deploy to GKE
      run: |
        gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER }} --zone ${{ secrets.GKE_ZONE }}
        kubectl set image deployment/backend backend=${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.GCLOUD_PROJECT }}/avatar-images/avatar-backend:$GITHUB_SHA
        kubectl set image deployment/frontend frontend=${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.GCLOUD_PROJECT }}/avatar-images/avatar-frontend:$GITHUB_SHA
        kubectl set image deployment/nginx frontend=${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.GCLOUD_PROJECT }}/avatar-images/avatar-nginx:$GITHUB_SHA
