FROM node:18 as build

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

ENV VITE_API_URL=http://backend:5000/api
ENV VITE_HOST=0.0.0.0
ENV VITE_PORT=5173
ENV VITE_CLIENT_PORT=5173

RUN npm run build

# Etapa 2: Servir la aplicación con Nginx
FROM nginx:stable-alpine

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]